---
abstract: 'Hook into opcode execution'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
configure_requires:
  ExtUtils::Depends: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: B-Hooks-OP-PPAddr
no_index:
  directory:
    - inc
    - t
requires:
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
